config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  resources :settings

  root 'posts#index'
  get  '/posts/sort/:type', to: 'posts#index'


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get 'profile', to: 'users#profile'

  get '/403', to: 'application#fourothree'


  # votes
  get '/post/:post_id/upvote', to: 'votes#upvote', format: :js
  get '/post/:post_id/downvote', to: 'votes#downvote', format: :js
  get '/comments/:comment_id/upvote', to: 'votes#upvote', format: :js
  get '/comments/:comment_id/downvote', to: 'votes#downvote',format: :js

  # comments
  post '/comments', to: 'comments#create', format: :js
  delete '/comments/:id', to: 'comments#destroy', format: :js
  get '/post/:post_id/comments/:id/new', to: 'comments#new', format: :js

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]

  has_many :posts
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :setting, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email    = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.nickname
      user.setting  = Setting.new
      
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restricted

  def profile
    @posts = Post.where(user_id: current_user.id)
  end
end

app/views/users/profile.html.erb
<p><%= current_user.username %></p>
<h2>Your posts</h2>
<ul class="user-posts">
<% @posts.each do |post| %>
  <li class="user-post">
    <a class="user-post-link" href="<%= post_path(post) %>"><%= post.title %></a>
    <a class="button-link orange" href="<%= edit_post_path(post) %>">Edit <i class="fas-top fas fa-edit"></i><i class="fas-bottom fas fa-arrow-alt-circle-right"></i></a>
    <a class="button-link red" href="<%= post_path(post) %>" data-method="delete" data-confirm="Are you sure?" rel="nofollow">Destroy <i class="fas-top fas fa-trash-alt"></i><i class="fas-bottom fas fa-arrow-alt-circle-right"></i></a>
  </li>
<% end %>
</ul>
<%= form_for(current_user.setting, remote: true) do |form| %>
  <h2>User settings</h2>
  <div class="user-settings">
    <div class="user-settings-save-alert">
      <div id="user-settings-alert">Saved!</div>
    </div>
    <div class="switch-visible-label">
      Code style: Dark theme
    </div>
    <div class="switch">
      <%= hidden_field_tag "setting[code_theme]", '' %>
      <% if current_user.setting.code_theme %>
        <input id="switcher" type="checkbox" class="switch-input" name="setting[code_theme]" type="hidden" value="<%= current_user.setting.code_theme %>" checked>
        <label for="switcher" class="switch-label">Code Style: Dark Theme</label>
      <% else %>
        <input id="switcher" type="checkbox" class="switch-input" name="setting[code_theme]" type="hidden" value="<%= current_user.setting.code_theme %>">
        <label for="switcher" class="switch-label">Code Style: Dark Theme</label>
      <% end %>
    </div>
  </div>
  <br/>
  <button type="submit" class="button">Save Settings <i class="fas-top fas fa-square"></i><i class="fas-bottom fas fa-check-square"></i></button>
<% end %>